import type { DashboardStats } from '../types/common.types'
import type { User } from '../types/user.types'
import type { SubscriptionPlan, Subscription } from '../types/subscription.types'
import type { PosterCategory, Poster, AutoGeneratedPoster } from '../types/poster.types'
import type { Festival } from '../types/festival.types'
import type { CreditTransaction } from '../types/credit.types'
import type { AIToolUsage } from '../types/ai-tool.types'
import type { Reel, MusicTrack } from '../types/reel.types'
import type { Notification as AppNotification } from '../types/notification.types'
import type { NearbyService, ServiceCategory } from '../types/service.types'

import type { StickerPack } from '../types/sticker.types'
import type { Tutorial, PolicyPage, ContactSubmission, PartnerInquiry, MallCategory, MallListing } from '../types/content.types'

export const mockDashboardStats: DashboardStats = {
  totalUsers: 12847,
  activeSubscriptions: 3421,
  expiredSubscriptions: 1876,
  revenueThisMonth: 847500,
  creditsConsumedToday: 1892,
  aiToolCallsToday: 456,
  activeReelsProcessing: 12,
  businessProfiles: 4521,
  totalPosters: 8934,
  userGrowth: [
    { date: '2026-02-15', count: 11200 },
    { date: '2026-02-22', count: 11580 },
    { date: '2026-03-01', count: 12100 },
    { date: '2026-03-08', count: 12450 },
    { date: '2026-03-15', count: 12847 },
  ],
  revenueByPlan: [
    { plan: 'Basic', revenue: 245000 },
    { plan: 'Pro', revenue: 412500 },
    { plan: 'Enterprise', revenue: 190000 },
  ],
  aiToolUsage: [
    { tool: 'Background Remove', count: 1245 },
    { tool: 'Caption Generate', count: 987 },
    { tool: 'Hashtag Generate', count: 856 },
    { tool: 'Photo Enhance', count: 654 },
    { tool: 'Poster Generate', count: 432 },
    { tool: 'Face Swap', count: 321 },
    { tool: 'Photo Generate', count: 198 },
  ],
  subscriptionDistribution: [
    { status: 'active', count: 3421 },
    { status: 'expired', count: 1876 },
    { status: 'cancelled', count: 543 },
    { status: 'failed', count: 128 },
  ],
}

const names = ['Rajesh Kumar', 'Priya Sharma', 'Amit Patel', 'Sneha Gupta', 'Vikram Singh', 'Anita Desai', 'Suresh Reddy', 'Meena Iyer', 'Karthik Nair', 'Deepa Joshi', 'Rahul Verma', 'Pooja Mehta', 'Arun Yadav', 'Kavita Rao', 'Manish Tiwari', 'Sunita Mishra', 'Naveen Kumar', 'Ritu Agarwal', 'Sanjay Dubey', 'Neha Pandey']
const cities = ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad', 'Jaipur', 'Lucknow']
const plans = ['free', 'basic', 'pro', 'enterprise'] as const

export const mockUsers: User[] = Array.from({ length: 20 }, (_, i) => ({
  id: i + 1,
  firebase_uid: `firebase_${1000 + i}`,
  email: `${names[i].toLowerCase().replace(' ', '.')}@email.com`,
  name: names[i],
  phone: `+91${9000000000 + Math.floor(Math.random() * 999999999)}`,
  avatar_url: null,
  is_premium: i < 8,
  plan: plans[i % 4],
  premium_since: i < 8 ? '2025-12-01T00:00:00Z' : null,
  premium_expiry: i < 8 ? '2026-12-01T00:00:00Z' : null,
  is_subscription_active: i < 8,
  referral_code: `BRD${1000 + i}`,
  referred_by: i > 5 ? Math.floor(Math.random() * 5) + 1 : null,
  credits: Math.floor(Math.random() * 500),
  is_active: true,
  is_deleted: false,
  total_downloads: Math.floor(Math.random() * 200),
  total_shares: Math.floor(Math.random() * 100),
  joined_at: `2025-${String(Math.floor(Math.random() * 12) + 1).padStart(2, '0')}-${String(Math.floor(Math.random() * 28) + 1).padStart(2, '0')}T00:00:00Z`,
  updated_at: '2026-03-15T00:00:00Z',
}))

export const mockPlans: SubscriptionPlan[] = [
  { id: 1, name: 'Basic Monthly', slug: 'basic-monthly', description: 'Perfect for getting started', price: 199, duration: 'monthly', duration_days: 30, credits_included: 50, features: ['50 poster downloads', 'Basic AI tools', 'Email support'], is_active: true, sort_order: 1, created_at: '2025-01-01T00:00:00Z' },
  { id: 2, name: 'Pro Monthly', slug: 'pro-monthly', description: 'For growing businesses', price: 499, duration: 'monthly', duration_days: 30, credits_included: 200, features: ['Unlimited downloads', 'All AI tools', 'Priority support', 'Custom branding'], is_active: true, sort_order: 2, created_at: '2025-01-01T00:00:00Z' },
  { id: 3, name: 'Pro Yearly', slug: 'pro-yearly', description: 'Best value for professionals', price: 4999, duration: 'yearly', duration_days: 365, credits_included: 2500, features: ['Unlimited downloads', 'All AI tools', 'Priority support', 'Custom branding', 'API access'], is_active: true, sort_order: 3, created_at: '2025-01-01T00:00:00Z' },
  { id: 4, name: 'Enterprise', slug: 'enterprise', description: 'For large teams', price: 9999, duration: 'yearly', duration_days: 365, credits_included: 10000, features: ['Everything in Pro', 'Dedicated manager', 'Custom integrations', 'SLA guarantee'], is_active: true, sort_order: 4, created_at: '2025-01-01T00:00:00Z' },
]

export const mockSubscriptions: Subscription[] = Array.from({ length: 15 }, (_, i) => ({
  id: i + 1,
  user: (i % 20) + 1,
  user_name: names[i % 20],
  user_phone: `+919${String(i).padStart(9, '0')}`,
  plan: (i % 4) + 1,
  plan_name: mockPlans[i % 4].name,
  razorpay_order_id: `order_${String(100000 + i)}`,
  razorpay_payment_id: `pay_${String(200000 + i)}`,
  razorpay_signature: `sig_${i}`,
  amount: mockPlans[i % 4].price,
  status: (['active', 'active', 'active', 'expired', 'cancelled', 'failed', 'active'] as const)[i % 7],
  starts_at: '2026-01-01T00:00:00Z',
  expires_at: '2026-04-01T00:00:00Z',
  is_active_subscription: i % 3 !== 0,
  created_at: `2026-0${(i % 3) + 1}-${String((i % 28) + 1).padStart(2, '0')}T00:00:00Z`,
}))

const posterCategories = ['Business', 'Festival', 'Social Media', 'Education', 'Food & Restaurant', 'Health & Fitness', 'Real Estate', 'Fashion']
export const mockPosterCategories: PosterCategory[] = posterCategories.map((name, i) => ({
  id: i + 1,
  name,
  slug: name.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-'),
  icon_url: null,
  description: `${name} poster templates`,
  sort_order: i + 1,
  is_active: true,
  poster_count: Math.floor(Math.random() * 200) + 20,
  parent: null,
  parent_name: null,
  children_count: 0,
}))

export const mockPosters: Poster[] = Array.from({ length: 20 }, (_, i) => ({
  id: i + 1,
  title: `${posterCategories[i % 8]} Poster ${i + 1}`,
  category: (i % 8) + 1,
  category_name: posterCategories[i % 8],
  thumbnail_url: `https://placehold.co/300x300/383838/FFC107?text=P${i + 1}`,
  image_url: `https://placehold.co/1080x1080/383838/FFC107?text=Poster+${i + 1}`,
  template_data: {},
  aspect_ratio: (['1:1', '4:5', '9:16', '16:9'] as const)[i % 4],
  tags: ['marketing', 'business'],
  is_premium: i % 3 === 0,
  download_count: Math.floor(Math.random() * 5000),
  share_count: Math.floor(Math.random() * 2000),
  festival: null,
  created_at: `2026-0${(i % 3) + 1}-${String((i % 28) + 1).padStart(2, '0')}T00:00:00Z`,
}))

export const mockAutoPosters: AutoGeneratedPoster[] = Array.from({ length: 10 }, (_, i) => ({
  id: i + 1,
  user: (i % 20) + 1,
  user_name: names[i % 20],
  poster: i + 1,
  poster_title: `Auto Poster ${i + 1}`,
  generated_image_url: `https://placehold.co/1080x1080/383838/FFC107?text=Auto+${i + 1}`,
  prompt_used: 'Business marketing poster for small shop',
  festival: null,
  festival_name: '',
  status: (['pending', 'generated', 'accepted', 'failed'] as const)[i % 4],
  credits_charged: 5,
  created_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`,
}))

export const mockFestivals: Festival[] = [
  { id: 1, name: 'Holi', slug: 'holi', description: 'Festival of Colors', date: '2026-03-17', banner_url: null, icon_url: null, is_active: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 2, name: 'Diwali', slug: 'diwali', description: 'Festival of Lights', date: '2026-10-20', banner_url: null, icon_url: null, is_active: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 3, name: 'Eid', slug: 'eid', description: 'Eid Mubarak', date: '2026-06-17', banner_url: null, icon_url: null, is_active: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 4, name: 'Independence Day', slug: 'independence-day', description: '15th August', date: '2026-08-15', banner_url: null, icon_url: null, is_active: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 5, name: 'Christmas', slug: 'christmas', description: 'Merry Christmas', date: '2026-12-25', banner_url: null, icon_url: null, is_active: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 6, name: 'New Year', slug: 'new-year', description: 'Happy New Year 2027', date: '2027-01-01', banner_url: null, icon_url: null, is_active: true, created_at: '2025-01-01T00:00:00Z' },
]

export const mockCreditTransactions: CreditTransaction[] = Array.from({ length: 15 }, (_, i) => ({
  id: i + 1,
  user: (i % 20) + 1,
  user_name: names[i % 20],
  transaction_type: (['purchase', 'usage', 'referral', 'subscription', 'bonus', 'usage'] as const)[i % 6],
  amount: (i % 2 === 0 ? 1 : -1) * (Math.floor(Math.random() * 50) + 1),
  balance_after: Math.floor(Math.random() * 500),
  description: ['Subscription credit', 'AI tool usage', 'Referral bonus', 'Credit purchase', 'Welcome bonus', 'Poster download'][i % 6],
  created_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`,
}))

export const mockAIToolUsage: AIToolUsage[] = Array.from({ length: 15 }, (_, i) => ({
  id: i + 1,
  user: (i % 20) + 1,
  user_name: names[i % 20],
  tool_type: (['background_remove', 'caption_generate', 'hashtag_generate', 'face_swap', 'photo_enhance', 'poster_generate', 'photo_generate'] as const)[i % 7],
  status: (['completed', 'completed', 'processing', 'failed', 'completed'] as const)[i % 5],
  credits_used: Math.floor(Math.random() * 10) + 1,
  processing_time_ms: Math.floor(Math.random() * 5000) + 500,
  created_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`,
}))

export const mockReels: Reel[] = Array.from({ length: 10 }, (_, i) => ({
  id: i + 1,
  user: (i % 20) + 1,
  user_name: names[i % 20],
  title: `Reel ${i + 1}`,
  source_poster: i + 1,
  video_url: null,
  thumbnail_url: `https://placehold.co/300x533/383838/FFC107?text=Reel+${i + 1}`,
  duration: Math.floor(Math.random() * 30) + 5,
  resolution: '1080x1920',
  animation_type: (['zoom_in', 'pan_left', 'fade', 'slide_up', 'ken_burns'] as const)[i % 5],
  music_track: (i % 5) + 1,
  music_track_name: `Track ${(i % 5) + 1}`,
  status: (['completed', 'processing', 'pending', 'failed', 'completed'] as const)[i % 5],
  credits_charged: 10,
  created_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`,
}))

export const mockMusicTracks: MusicTrack[] = Array.from({ length: 8 }, (_, i) => ({
  id: i + 1,
  name: ['Upbeat Business', 'Festival Joy', 'Motivational Rise', 'Trending Beat', 'Corporate Clean', 'Festive Drums', 'Inspirational Piano', 'Modern Pop'][i],
  file_url: '#',
  duration: Math.floor(Math.random() * 120) + 30,
  category: (['business', 'festive', 'motivational', 'trending'] as const)[i % 4],
  is_premium: i % 3 === 0,
  created_at: '2025-06-01T00:00:00Z',
}))

export const mockNotifications: AppNotification[] = Array.from({ length: 10 }, (_, i) => ({
  id: i + 1,
  user: (i % 20) + 1,
  user_email: `user${(i % 20) + 1}@example.com`,
  title: ['New Festival Coming!', 'Your poster is ready', 'Subscription expiring', 'Welcome to Brandnio', 'Credit bonus added'][i % 5],
  body: 'Notification body text here with details about the event.',
  notification_type: (['general', 'promo', 'system', 'brand_match', 'follow'] as const)[i % 5],
  image_url: null,
  action_url: null,
  is_read: i % 2 === 0,
  data: {},
  created_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`,
}))

const serviceCategories = ['Printing', 'Photography', 'Web Design', 'Catering', 'Accounting', 'Legal Services']
export const mockServiceCategories: ServiceCategory[] = serviceCategories.map((name, i) => ({
  id: i + 1, name, slug: name.toLowerCase().replace(/ /g, '-'), icon_url: null, description: `${name} services`, sort_order: i + 1, is_active: true, service_count: Math.floor(Math.random() * 50) + 5,
}))

export const mockServices: NearbyService[] = Array.from({ length: 10 }, (_, i) => ({
  id: i + 1, owner: (i % 20) + 1, owner_name: names[i % 20], category: (i % 6) + 1, category_name: serviceCategories[i % 6], name: `${names[i % 20]}'s ${serviceCategories[i % 6]}`, description: 'Quality services for your business', phone: '+919000000000', email: 'service@example.com', website: '', address: `${i + 1} Main Street`, city: cities[i % 10], state: 'Maharashtra', pincode: '400001', latitude: 19.076, longitude: 72.877, images: [], average_rating: Math.round((3 + Math.random() * 2) * 10) / 10, review_count: Math.floor(Math.random() * 50), is_verified: i % 3 === 0, is_active: true, created_at: '2025-06-01T00:00:00Z',
}))


export const mockStickerPacks: StickerPack[] = Array.from({ length: 8 }, (_, i) => ({
  id: i + 1, name: `Sticker Pack ${i + 1}`, slug: `sticker-pack-${i + 1}`, description: `A fun sticker pack #${i + 1}`, cover_image_url: null, icon_url: null, category: ['emoji', 'business', 'festival', 'fun'][i % 4], tabs: 'all', is_premium: i % 3 === 0, download_count: Math.floor(Math.random() * 5000), sort_order: i + 1, sticker_count: Math.floor(Math.random() * 20) + 5, is_active: true, created_at: '2025-06-01T00:00:00Z', updated_at: '2025-06-01T00:00:00Z',
}))


export const mockTutorials: Tutorial[] = Array.from({ length: 5 }, (_, i) => ({
  id: i + 1, title: `How to ${['Create Posters', 'Use AI Tools', 'Schedule Festivals', 'Generate Reels', 'Set Up Business Profile'][i]}`, slug: `tutorial-${i + 1}`, description: 'Step by step guide', content: '<p>Tutorial content here...</p>', thumbnail_url: null, video_url: null, sort_order: i + 1, is_active: true, created_at: '2025-06-01T00:00:00Z',
}))

export const mockPolicies: PolicyPage[] = [
  { id: 1, title: 'Terms of Service', slug: 'terms', policy_type: 'terms', content: '<h1>Terms of Service</h1><p>...</p>', version: '1.0', is_active: true, updated_at: '2025-06-01T00:00:00Z' },
  { id: 2, title: 'Privacy Policy', slug: 'privacy', policy_type: 'privacy', content: '<h1>Privacy Policy</h1><p>...</p>', version: '1.0', is_active: true, updated_at: '2025-06-01T00:00:00Z' },
  { id: 3, title: 'Refund Policy', slug: 'refund', policy_type: 'refund', content: '<h1>Refund Policy</h1><p>...</p>', version: '1.0', is_active: true, updated_at: '2025-06-01T00:00:00Z' },
]

export const mockContactSubmissions: ContactSubmission[] = Array.from({ length: 8 }, (_, i) => ({
  id: i + 1, user: (i % 20) + 1, user_name: names[i % 20], name: names[i % 20], email: `user${i}@email.com`, phone: '+919000000000', subject: (['general', 'bug', 'feature', 'billing', 'other'] as const)[i % 5], message: 'I have an issue with my account...', is_resolved: i % 3 === 0, admin_notes: i % 3 === 0 ? 'Resolved via email' : '', created_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`,
}))

export const mockPartnerInquiries: PartnerInquiry[] = Array.from({ length: 5 }, (_, i) => ({
  id: i + 1, user: (i % 20) + 1, user_name: names[i % 20], name: names[i % 20], email: `partner${i}@company.com`, phone: '+919000000000', company_name: `Company ${i + 1}`, partner_type: (['reseller', 'affiliate', 'agency', 'enterprise', 'other'] as const)[i % 5], message: 'We are interested in partnering...', is_reviewed: i % 2 === 0, admin_notes: '', created_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`,
}))

export const mockMallCategories: MallCategory[] = [
  { id: 1, name: 'Electronics', slug: 'electronics', icon_url: null, sort_order: 1, is_active: true, listing_count: 15 },
  { id: 2, name: 'Clothing', slug: 'clothing', icon_url: null, sort_order: 2, is_active: true, listing_count: 25 },
  { id: 3, name: 'Food', slug: 'food', icon_url: null, sort_order: 3, is_active: true, listing_count: 18 },
]

export const mockMallListings: MallListing[] = Array.from({ length: 10 }, (_, i) => ({
  id: i + 1, user: (i % 20) + 1, user_email: `user${i + 1}@example.com`, category: (i % 3) + 1, title: `Product Listing ${i + 1}`, subtitle: 'Quality service', description: 'Great product for your needs', price: String(Math.floor(Math.random() * 5000) + 100), discount_price: i % 3 === 0 ? String(Math.floor(Math.random() * 3000) + 50) : null, images: [], contact_phone: '+919000000000', contact_whatsapp: '+919000000000', city: cities[i % 10], turnaround_hours: 24, service_highlight_badge: '', inclusions: [], feature_tags: [], is_featured: i % 4 === 0, is_active: true, view_count: Math.floor(Math.random() * 500), created_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`, updated_at: `2026-03-${String((i % 15) + 1).padStart(2, '0')}T00:00:00Z`,
}))
