export type AspectRatio = '1:1' | '4:5' | '9:16' | '16:9'
export type AutoPosterStatus = 'pending' | 'generated' | 'accepted' | 'failed'
export type FestivalPosterStatus = 'scheduled' | 'generated' | 'sent' | 'failed'

export interface PosterCategory {
  id: number
  name: string
  slug: string
  icon_url: string | null
  description: string
  sort_order: number
  is_active: boolean
  poster_count: number
}

export interface Poster {
  id: number
  title: string
  category: number
  category_name: string
  thumbnail_url: string
  image_url: string
  template_data: Record<string, unknown>
  aspect_ratio: AspectRatio
  tags: string[]
  is_premium: boolean
  download_count: number
  share_count: number
  festival: number | null
  created_at: string
}

export interface AutoGeneratedPoster {
  id: number
  user: number
  user_name: string
  poster: number | null
  poster_title: string
  generated_image_url: string | null
  prompt_used: string
  festival: number | null
  festival_name: string
  status: AutoPosterStatus
  credits_charged: number
  created_at: string
}

export interface FestivalPoster {
  id: number
  user: number
  user_name: string
  festival: number
  festival_name: string
  festival_date: string
  status: FestivalPosterStatus
  auto_share: boolean
  scheduled_date: string
  scheduled_time: string
  created_at: string
}
