// Keep in sync with the dropdown options in PosterListPage.tsx
// (Add modal + Bulk Upload modal) and the resolveCanvasDims() lookup in
// TemplateLayerEditor.tsx. Backend's posters.models.detect_aspect_ratio()
// can emit any of these.
export type AspectRatio =
  | '1:1' | '4:5' | '9:16' | '16:9'
  | '2:3' | '3:2' | '3:4' | '4:3'
  | '2:1' | '1:2' | '2.35:1'
export type AutoPosterStatus = 'pending' | 'generated' | 'accepted' | 'failed'
export type FestivalPosterStatus = 'scheduled' | 'generated' | 'sent' | 'failed'
export type PosterScope = 'home' | 'categories' | 'business' | 'festival' | 'greeting'

export interface PosterCategory {
  id: number
  name: string
  slug: string
  icon_url: string | null
  description: string
  sort_order: number
  is_active: boolean
  show_in_home: boolean
  show_in_create: boolean
  section_type: string
  parent: number | null
  parent_name: string | null
  children_count: number
  poster_count: number
}

export interface Poster {
  id: number
  title: string
  category: number
  category_name: string
  thumbnail_url: string | null
  image_url: string | null
  template_data: Record<string, unknown>
  aspect_ratio: AspectRatio
  // True image pixel dimensions captured at upload time. Used by the
  // layer editor's canvas to size at the actual aspect ratio rather
  // than the coarse `aspect_ratio` enum (which buckets a 1080×1200
  // image as `1:1` and would distort layer positions). Both renderers
  // (admin + Android) prefer these when non-zero.
  image_width: number
  image_height: number
  tags: string[]
  is_premium: boolean
  is_active: boolean
  scope: PosterScope
  language: number | null
  language_name: string
  language_code: string
  download_count: number
  share_count: number
  festival: number | null
  created_at: string
}

export interface AutoGeneratedPoster {
  id: number
  user: number
  user_name: string
  poster: number | null
  poster_title: string
  generated_image_url: string | null
  prompt_used: string
  festival: number | null
  festival_name: string
  status: AutoPosterStatus
  credits_charged: number
  created_at: string
}

export interface HomeBanner {
  id: number
  title: string
  cta_text: string
  preview_image_1: string | null
  preview_image_2: string | null
  preview_image_3: string | null
  preview_image_4: string | null
  preview_image_5: string | null
  preview_image_6: string | null
  gradient_start_color: string | null
  gradient_center_color: string | null
  gradient_end_color: string | null
  target_category_slug: string | null
  target_category_name: string | null
  position_after_section: number
  sort_order: number
  is_active: boolean
  created_at: string
}

export interface FestivalPoster {
  id: number
  user: number
  user_name: string
  festival: number
  festival_name: string
  festival_date: string
  status: FestivalPosterStatus
  auto_share: boolean
  scheduled_date: string
  scheduled_time: string
  created_at: string
}

export interface HomeCard {
  id: number
  card_type: string
  title: string
  image_url: string
  redirect_slug: string
  sort_order: number
  is_active: boolean
}

export interface HomeCardSection {
  id: number
  section_key: string
  title: string
  subtitle: string
  badge_text: string
  cta_text: string
  redirect_slug: string
  sort_order: number
  is_active: boolean
}

export interface PromoAnnouncement {
  id: number
  text: string
  subtitle: string
  is_active: boolean
  sort_order: number
}
