import type { PoliticianProfile } from './content.types'

export type PlanType = 'free' | 'basic' | 'pro' | 'enterprise'

export interface User {
  id: number
  firebase_uid: string
  email: string
  name: string
  phone: string
  avatar_url: string | null
  is_premium: boolean
  plan: PlanType
  premium_since: string | null
  premium_expiry: string | null
  is_subscription_active: boolean
  referral_code: string
  referred_by: number | null
  credits: number
  total_downloads: number
  total_shares: number
  is_active: boolean
  is_deleted: boolean
  joined_at: string
  updated_at: string
  /** Pillar 2: Last time user made an authenticated API call (debounced 5min).
   *  null = never seen since the feature shipped. */
  last_seen_at: string | null
}

export interface BusinessProfile {
  id: number
  user: number
  user_name?: string
  user_email?: string
  user_avatar?: string
  business_name: string
  tagline: string
  logo_url: string | null
  /** WebP thumbnail of logo (auto-generated by backend, 512px max side, q=80). */
  logo_thumb_url?: string | null
  category: string                    // matches backend BusinessProfile.CATEGORY_CHOICES
  email: string
  phone: string
  website: string
  /** Phase 1 (2026-04): role / job title — rendered on poster frames with a
   *  "designation" text area. Added alongside the Poster Frame redesign. */
  designation?: string
  address: string
  city: string
  state: string
  pincode: string
  // Field names corrected to match backend model (no _url suffix on social)
  facebook: string
  instagram: string
  twitter: string                     // NEW — backend field added in 0015 migration
  youtube: string
  whatsapp: string
  /** Phase 1 (2026-04): Pinterest URL for the 7th toggle-icon. */
  pinterest?: string
  username?: string
  show_phone_number?: boolean
  linkedin?: string
  /** Phase 2 (2026-04 / G6): server-computed weighted fullness 0..100. */
  completion_score?: number
  /** Phase 3 (2026-04 / G7): True once the user saved any non-empty field.
   *  Distinguishes an actually-touched profile from the auto-created
   *  placeholder row returned by get_or_create on first login. */
  has_been_filled?: boolean
  /** Legacy CSV (auto-mirrored from industries_m2m). Use industries_m2m for writes. */
  industries?: string
  /** Canonical M2M field — array of BusinessIndustry slugs. */
  industries_m2m?: string[]
  // Extended brand fields (TextField + URLField + CSV)
  products_and_services?: string
  extra_element_url?: string
  /** CSV of social icon keys to render: facebook,instagram,whatsapp,youtube,x,linkedin,pinterest */
  selected_social_icons?: string
  is_complete?: boolean
  created_at?: string
  updated_at?: string
}

export interface UserCustomFrame {
  id: number
  user: number
  user_email: string
  name: string
  category: string
  frame_type: string
  frame_image: string
  frame_image_url: string
  is_active: boolean
  created_by: number | null
  created_by_email: string | null
  created_at: string
  updated_at: string
}

export interface UserSubscriptionSummary {
  id: number
  plan_id: number
  plan_name: string
  plan_slug: string
  price: string
  duration_days: number
  status: string
  starts_at: string | null
  expires_at: string | null
  days_remaining: number
}

export interface UserDetails {
  user: User
  active_subscription: UserSubscriptionSummary | null
  business_profile: BusinessProfile | null
  political_profile: PoliticianProfile | null
  custom_frames: UserCustomFrame[]
}
