import { DataTable, type Column } from '../../components/ui/DataTable'
import { StatusBadge } from '../../components/ui/StatusBadge'
import { mockAutoPosters } from '../../services/mock-data'
import { formatDate } from '../../utils/formatters'
import type { AutoGeneratedPoster } from '../../types'

const columns: Column<AutoGeneratedPoster>[] = [
  { key: 'user_name', title: 'User', sortable: true },
  { key: 'poster_title', title: 'Poster' },
  { key: 'status', title: 'Status', render: (p) => <StatusBadge status={p.status as string} /> },
  { key: 'credits_charged', title: 'Credits' },
  { key: 'created_at', title: 'Generated', sortable: true, render: (p) => formatDate(p.created_at as string) },
]

export default function AutoPosterMonitorPage() {
  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold text-brand-text">Auto-Generated Posters</h1>
      <div className="bg-brand-dark-card rounded-xl border border-brand-dark-border/50">
        <DataTable columns={columns} data={mockAutoPosters} />
      </div>
    </div>
  )
}
